### ISSUE TITLE
Error running export tool

### ISSUE THREAD

**Issue by iHaagcom** [ichensky/msteams_history#7]
Error Acquiring Token:
MSAL.Desktop.4.4.0.0.MsalClientException: 
	ErrorCode: authentication_ui_failed
Microsoft.Identity.Client.MsalClientException: The browser based authentication dialog failed to complete. Reason: The protocol is not known and no pluggable protocols have been entered that match.
   at Microsoft.Identity.Client.Platforms.net45.WindowsFormsWebAuthenticationDialog.ShowBrowser()
   at Microsoft.Identity.Client.Platforms.net45.WindowsFormsWebAuthenticationDialog.OnAuthenticate()
   at Microsoft.Identity.Client.Platforms.net45.WindowsFormsWebAuthenticationDialogBase.AuthenticateAAD(Uri requestUri, Uri callbackUri)
   at Microsoft.Identity.Client.Platforms.net45.InteractiveWebUI.OnAuthenticate()
   at Microsoft.Identity.Client.Platforms.net45.WebUI.Authenticate(Uri requestUri, Uri callbackUri)
   at Microsoft.Identity.Client.Platforms.net45.WebUI.<>c__DisplayClass20_0.<AcquireAuthorizationAsync>b__1(Object tcs)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Platforms.net45.WebUI.<AcquireAuthorizationAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<AcquireAuthorizationAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

**Comment by iHaagcom** [comment]
Run as admin
